-- CreateTable
CREATE TABLE "ReferralsAndServices" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "parentingClasses" JSONB NOT NULL,
    "transportationServices" JSONB NOT NULL,
    "ssiDisability" JSONB NOT NULL,
    "temporaryAssistanceForNeedyFamilies" JSONB NOT NULL,
    "personalSafety" JSONB NOT NULL,
    "homeVisitationProgram" JSONB NOT NULL,
    "housingAssistance" JSONB NOT NULL,
    "healthyStartProgram" JSONB NOT NULL,
    "supportServicesOther" JSONB NOT NULL,
    "breastfeedingSupport" JSONB NOT NULL,
    "localFoodPantries" JSONB NOT NULL,
    "snap" JSONB NOT NULL,
    "womenInfantsAndChildren" JSONB NOT NULL,
    "foodNutritionOther" JSONB NOT NULL,
    "healthInsuranceEnrollment" JSONB NOT NULL,
    "prenatalHealthcare" JSONB NOT NULL,
    "familyPlanning" JSONB NOT NULL,
    "primaryCare" JSONB NOT NULL,
    "mentalHealthCounseling" JSONB NOT NULL,
    "smokingCessation" JSONB NOT NULL,
    "healthcareOther" JSONB NOT NULL,
    "residential" JSONB NOT NULL,
    "outpatient" JSONB NOT NULL,
    "caringForTwoProgram" JSONB NOT NULL,
    "theCradlesProgram" JSONB NOT NULL,
    "recoverySupportServices" JSONB NOT NULL,
    "medicationAssistedTreatment" JSONB NOT NULL,
    "substanceUseTreatmentOther" JSONB NOT NULL,
    "earlyChildhoodIntervention" JSONB NOT NULL,
    "earlyHeadStart" JSONB NOT NULL,
    "nciChildcareSubsidy" JSONB NOT NULL,
    "pediatricianPrimaryCare" JSONB NOT NULL,
    "safeSleepEducation" JSONB NOT NULL,
    "childRelatedOther" JSONB NOT NULL,
    "childProtectiveService" JSONB NOT NULL,
    "legalAid" JSONB NOT NULL,
    "specialtyCourt" JSONB NOT NULL,
    "legalAssistanceOther" JSONB NOT NULL,
    "additionalNotes" JSONB NOT NULL,
    "dateCreated" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "dateModified" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "ReferralsAndServices_pkey" PRIMARY KEY ("id")
);

-- AddForeignKey
ALTER TABLE "ReferralsAndServices" ADD CONSTRAINT "ReferralsAndServices_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
